export const PROVIDERS_ADD = "PROVIDERS_ADD";
export const PROVIDERS_REMOVE = "PROVIDERS_REMOVE";
export const PROVIDERS_TABLE_TOGGLE_ROW = "PROVIDERS_TABLE_TOGGLE_ROW";
export const PROVIDERS_FORM_UPDATE = "PROVIDERS_FORM_UPDATE";
